// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Students.proto

package com.rain.netty.grpc;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rain.netty.grpc.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
