// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Students.proto

package com.rain.netty.grpc;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rain.netty.grpc.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 1;</code>
   */
  String getResponseInfo();
  /**
   * <code>string response_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
