// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Students.proto

package com.rain.netty.grpc;

public interface StudentsAgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rain.netty.grpc.StudentsAge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
